global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'go-api'
    static_configs:
      - targets: ['go-api:8080']

  - job_name: 'kafka-exporter'
    static_configs:
      - targets: ['kafka-exporter:9308']
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9404']